{
    "openapi": "3.0.3",
    "info": {
        "title": "TODO List",
        "version": "1.0.0",
        "description": "OPEN API for Todo List",
        "termsOfService": "https://github.com/baihaqiyazid",
        "contact": {
            "name": "Muhammad Yazid Baihaqi",
            "email": "baihaqiyazid16@gmail.com",
            "url": "https://github.com/baihaqiyazid"
        },
        "license": {
            "name": "apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers": [
        {
            "description": "Todo List RESTFul API Server",
            "url": "https://{environtment}.programmerzamannow.com/api/v1",
            "variables": {
                "environtment": {
                    "description": "Server Environtment",
                    "default": "dev",
                    "enum": [
                        "dev",
                        "qa",
                        "prod"
                    ]
                }
            }
        }
    ],
    "paths": {
        "/todolist": {
            "get": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Get All Todo List",
                "description": "Get All Active Todo by default",
                "parameters": [
                    {
                        "name": "include_done",
                        "in": "query",
                        "required": false,
                        "description": "Get all include done todo",
                        "schema": {
                            "type": "boolean",
                            "nullable": true,
                            "default": false
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter todo by name",
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "Go": {
                                "value": "go",
                                "description": "examples todo with name Go"
                            },
                            "Flutter": {
                                "value": "flutter",
                                "description": "examples todo with name Flutter"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Get All Todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ArrayTodolist"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example Success get all todo",
                                        "value": [
                                            {
                                                "id": 1,
                                                "name": "Golang",
                                                "priority": 3,
                                                "tags": [
                                                    "Golang",
                                                    "Programming"
                                                ]
                                            },
                                            {
                                                "id": 1,
                                                "name": "PHP",
                                                "priority": 3,
                                                "tags": [
                                                    "php",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Create Todo List",
                "description": "Create Active Todo",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdate"
                            },
                            "examples": {
                                "Go": {
                                    "value": {
                                        "name": "Go",
                                        "priority": 3,
                                        "tags": [
                                            "go",
                                            "c",
                                            "programming"
                                        ]
                                    },
                                    "description": "examples todo with name Go"
                                },
                                "Flutter": {
                                    "value": {
                                        "name": "flutter",
                                        "priority": 3,
                                        "tags": [
                                            "flutter",
                                            "c",
                                            "programming"
                                        ]
                                    },
                                    "description": "examples todo with name flutter"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success Create Todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "Go": {
                                        "description": "Success Create Go todolist",
                                        "value": {
                                            "id": 1,
                                            "name": "Go",
                                            "priority": 3,
                                            "tags": [
                                                "go",
                                                "c",
                                                "programming"
                                            ]
                                        }
                                    },
                                    "Flutter": {
                                        "description": "Success Create flutter todolist",
                                        "value": {
                                            "id": 2,
                                            "name": "flutter",
                                            "priority": 3,
                                            "tags": [
                                                "flutter",
                                                "c",
                                                "programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/todolist/{todolistId}": {
            "put": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Update Todo List",
                "description": "Update one todo by default",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/TodolistId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdate"
                            }
                        },
                        "examples": {
                            "Go": {
                                "value": {
                                    "name": "Go",
                                    "priority": 3,
                                    "tags": [
                                        "go",
                                        "c",
                                        "programming"
                                    ]
                                },
                                "description": "examples todo with name Go"
                            },
                            "Flutter": {
                                "value": {
                                    "name": "flutter",
                                    "priority": 3,
                                    "tags": [
                                        "flutter",
                                        "c",
                                        "programming"
                                    ]
                                },
                                "description": "examples todo with name flutter"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success Update Todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer",
                                            "format": "int64"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "priority": {
                                            "type": "number"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Go": {
                                        "description": "Success Create Go todolist",
                                        "value": {
                                            "id": 1,
                                            "name": "Go",
                                            "priority": 3,
                                            "tags": [
                                                "go",
                                                "c",
                                                "programming"
                                            ]
                                        }
                                    },
                                    "Flutter": {
                                        "description": "Success Create flutter todolist",
                                        "value": {
                                            "id": 2,
                                            "name": "flutter",
                                            "priority": 3,
                                            "tags": [
                                                "flutter",
                                                "c",
                                                "programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Delete Todo List",
                "description": "Delete Active Todo by default",
                "parameters": [
                    {
                        "name": "todolistId",
                        "in": "path",
                        "required": true,
                        "description": "id for delete todo",
                        "schema": {
                            "type": "string",
                            "minLength": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Deleted Todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success Delete Todo",
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failed Delete. Todolist Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Failed Delete Todo",
                                        "value": {
                                            "success": false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "TodolistAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key",
                "description": "Authentication For RESTFul Api Todolist"
            }
        },
        "parameters": {
            "TodolistId": {
                "name": "todolistId",
                "in": "path",
                "required": true,
                "description": "id for update todo",
                "schema": {
                    "type": "string",
                    "minLength": 1
                },
                "examples": {
                    "Go": {
                        "description": "Put id Go",
                        "value": "1"
                    },
                    "Flutter": {
                        "description": "Put id Flutter",
                        "value": "2"
                    }
                }
            }
        },
        "schemas": {
            "Todolist": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "name": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "number"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "CreateOrUpdate": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "minLength": 3,
                        "required": true
                    },
                    "priority": {
                        "type": "integer",
                        "format": "int32",
                        "default": 1,
                        "maxLength": 3,
                        "required": false
                    },
                    "tags": {
                        "type": "array",
                        "minItems": 1,
                        "required": false,
                        "items": {
                            "type": "string",
                            "minLength": 1
                        }
                    }
                }
            },
            "ArrayTodolist": {
                "$ref": "#/components/schemas/Todolist"
            }
        }
    }
}